
package com.example.demo.junit.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PointService", targetNamespace = "http://bean.demo.example.com/", wsdlLocation = "http://127.0.0.1:9999/point?wsdl")
public class PointService
    extends Service
{

    private final static URL POINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException POINTSERVICE_EXCEPTION;
    private final static QName POINTSERVICE_QNAME = new QName("http://bean.demo.example.com/", "PointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/point?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POINTSERVICE_WSDL_LOCATION = url;
        POINTSERVICE_EXCEPTION = e;
    }

    public PointService() {
        super(__getWsdlLocation(), POINTSERVICE_QNAME);
    }

    public PointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POINTSERVICE_QNAME, features);
    }

    public PointService(URL wsdlLocation) {
        super(wsdlLocation, POINTSERVICE_QNAME);
    }

    public PointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POINTSERVICE_QNAME, features);
    }

    public PointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Point
     */
    @WebEndpoint(name = "PointPort")
    public Point getPointPort() {
        return super.getPort(new QName("http://bean.demo.example.com/", "PointPort"), Point.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Point
     */
    @WebEndpoint(name = "PointPort")
    public Point getPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bean.demo.example.com/", "PointPort"), Point.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POINTSERVICE_EXCEPTION!= null) {
            throw POINTSERVICE_EXCEPTION;
        }
        return POINTSERVICE_WSDL_LOCATION;
    }

}
