
package com.example.demo.junit.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Point", targetNamespace = "http://bean.demo.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Point {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.AddResponse")
    @Action(input = "http://bean.demo.example.com/Point/addRequest", output = "http://bean.demo.example.com/Point/addResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setX", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.SetX")
    @ResponseWrapper(localName = "setXResponse", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.SetXResponse")
    @Action(input = "http://bean.demo.example.com/Point/setXRequest", output = "http://bean.demo.example.com/Point/setXResponse")
    public void setX(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setY", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.SetY")
    @ResponseWrapper(localName = "setYResponse", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.SetYResponse")
    @Action(input = "http://bean.demo.example.com/Point/setYRequest", output = "http://bean.demo.example.com/Point/setYResponse")
    public void setY(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getX", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.GetX")
    @ResponseWrapper(localName = "getXResponse", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.GetXResponse")
    @Action(input = "http://bean.demo.example.com/Point/getXRequest", output = "http://bean.demo.example.com/Point/getXResponse")
    public String getX();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getY", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.GetY")
    @ResponseWrapper(localName = "getYResponse", targetNamespace = "http://bean.demo.example.com/", className = "com.example.demo.junit.webservice.GetYResponse")
    @Action(input = "http://bean.demo.example.com/Point/getYRequest", output = "http://bean.demo.example.com/Point/getYResponse")
    public String getY();

}
